"""
Markdown reporter - for GitHub, GitLab, and documentation.
"""

from typing import Optional, Dict, Any, List
from pathlib import Path
import logging

from models.scan_context import ScanContext
from reporting.base_reporter import BaseReporter


logger = logging.getLogger(__name__)


class MarkdownReporter(BaseReporter):
    """
    Markdown reporter for documentation and version control systems.
    Good for GitHub/GitLab issues and READMEs.
    """
    
    def __init__(self):
        super().__init__()
    
    def get_name(self) -> str:
        return "MarkdownReporter"
    
    def get_extension(self) -> str:
        return "md"
    
    def generate_report(self, context: ScanContext, output_path: Optional[Path] = None) -> Path:
        """
        Generate Markdown report.
        """
        logger.info("Generating Markdown report...")
        
        # Prepare data
        report_data = self._prepare_report_data(context)
        
        # Determine output path
        output_file = self._ensure_output_dir(output_path)
        
        # Generate Markdown
        markdown_content = self._generate_markdown_content(report_data)
        
        try:
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(markdown_content)
            
            logger.info(f"Markdown report saved to: {output_file}")
            return output_file
            
        except Exception as e:
            logger.error(f"Failed to generate Markdown report: {e}")
            raise
    
    def _generate_markdown_content(self, report_data: Dict[str, Any]) -> str:
        """Generate full Markdown content."""
        timestamp = report_data['metadata']['generated_at'].replace('T', ' ')[:19]
        
        return f"""# Security Scan Report

Generated: {timestamp}  
Target: `{report_data['metadata']['scan_target']}`  
Mode: {report_data['metadata']['scan_mode'].upper()}  
Duration: {self._format_duration(report_data['metadata']['duration_seconds'])}

---

## 📊 Executive Summary

**Risk Score:** **{report_data['metadata']['risk_score']:.1f}/100**

| Severity | Count |
|----------|-------|
| 🔴 Critical | {report_data['summary']['critical_count']} |
| 🟠 High | {report_data['summary']['high_count']} |
| 🟡 Medium | {report_data['summary']['medium_count']} |
| 🟢 Low | {report_data['summary']['low_count']} |
| 🔵 Info | {report_data['summary']['info_count']} |
| **Total** | **{report_data['summary']['total_findings']}** |

**Files Scanned:** {report_data['summary']['total_files_scanned']}  
**Files with Findings:** {report_data['summary']['files_with_findings']}

---

## 📈 Findings by Category

{self._generate_category_table(report_data)}

---

## 🔍 Detailed Findings

{self._generate_findings_details(report_data['all_findings'])}

---

## 📁 Findings by File

{self._generate_files_details(report_data['findings_by_file'])}

---

## ⚙️ Scan Configuration

| Setting | Value |
|---------|-------|
| Target | `{report_data['metadata']['scan_target']}` |
| Mode | {report_data['metadata']['scan_mode'].upper()} |
| Duration | {self._format_duration(report_data['metadata']['duration_seconds'])} |
| Files Collected | {report_data['scan_statistics']['files_collected']} |
| Files Processed | {report_data['scan_statistics']['files_processed']} |

---

*Generated by Security Scanner v{report_data['metadata']['tool_version']}*  
*⚠️ This report contains sensitive security information. Handle with care.*
"""
    
    def _generate_category_table(self, report_data: Dict[str, Any]) -> str:
        """Generate Markdown table for categories."""
        # Count by category
        category_counts = {}
        for finding in report_data['all_findings']:
            category = finding['category']
            category_counts[category] = category_counts.get(category, 0) + 1
        
        # Sort by count
        sorted_categories = sorted(category_counts.items(), key=lambda x: x[1], reverse=True)
        
        if not sorted_categories:
            return "*No findings by category*"
        
        table = "| Category | Count |\n|----------|-------|\n"
        for category, count in sorted_categories[:15]:  # Top 15
            table += f"| {category} | {count} |\n"
        
        if len(sorted_categories) > 15:
            table += f"| *{len(sorted_categories) - 15} more categories* | |\n"
        
        return table
    
    def _generate_findings_details(self, findings: List[Dict[str, Any]]) -> str:
        """Generate detailed findings in Markdown."""
        if not findings:
            return "**No findings detected.**"
        
        # Group by severity
        by_severity = {}
        for finding in findings:
            severity = finding['severity']
            if severity not in by_severity:
                by_severity[severity] = []
            by_severity[severity].append(finding)
        
        # Generate sections for each severity
        sections = []
        for severity in ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO']:
            if severity in by_severity:
                severity_findings = by_severity[severity]
                sections.append(f"### {self._get_severity_icon(severity)} {severity} Findings ({len(severity_findings)})")
                
                for i, finding in enumerate(severity_findings, 1):
                    sections.append(self._generate_finding_markdown(finding, i))
        
        return '\n\n'.join(sections)
    
    def _generate_finding_markdown(self, finding: Dict[str, Any], index: int) -> str:
        """Generate Markdown for a single finding."""
        confidence_percent = int(finding['confidence'] * 100)
        
        # Format code snippet
        code_snippet = ""
        if finding.get('code_snippet'):
            # Escape backticks in code
            escaped_code = finding['code_snippet'].replace('`', '\\`')
            code_snippet = f"\n```\n{escaped_code}\n```\n"
        
        # Format context
        context = ""
        if finding.get('context_before') or finding.get('context_after'):
            context_parts = []
            if finding.get('context_before'):
                context_parts.append(f"**Before:**\n```\n{finding['context_before']}\n```")
            if finding.get('context_after'):
                context_parts.append(f"**After:**\n```\n{finding['context_after']}\n```")
            context = "\n" + "\n\n".join(context_parts) + "\n"
        
        # Tags
        tags = ""
        if finding.get('tags'):
            tags = f"\n**Tags:** `{'`, `'.join(finding['tags'])}`\n"
        
        return f"""#### {index}. {finding['title']}

**Severity:** `{finding['severity']}`  
**Category:** `{finding['category']}`  
**Confidence:** `{confidence_percent}%`  
**Location:** `{finding['file_path']}:{finding['line_start']}`  
**Rule:** `{finding.get('rule_id', 'N/A')}`  
**Detector:** `{finding.get('detector_name', 'Unknown')}`  
**ID:** `{finding['id'][:8]}`

**Description:**  
{finding['description']}

**Recommendation:**  
{finding['recommendation']}
{code_snippet}{context}{tags}
---"""
    
    def _generate_files_details(self, findings_by_file: Dict[str, List[Dict[str, Any]]]) -> str:
        """Generate files details in Markdown."""
        if not findings_by_file:
            return "**No files with findings.**"
        
        sections = ["### Files with Findings"]
        
        for file_path, findings in findings_by_file.items():
            # Count severities
            severity_counts = {}
            for finding in findings:
                severity = finding['severity']
                severity_counts[severity] = severity_counts.get(severity, 0) + 1
            
            # Create severity badges
            badges = []
            for severity in ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO']:
                count = severity_counts.get(severity, 0)
                if count > 0:
                    badges.append(f"{self._get_severity_icon(severity)} {severity}: {count}")
            
            sections.append(f"#### `{file_path}`")
            sections.append(f"**Findings:** {len(findings)} ({', '.join(badges)})")
            
            # List findings
            for i, finding in enumerate(findings, 1):
                sections.append(f"{i}. **{finding['title']}** ({finding['severity']}) - Line {finding['line_start']}")
            
            sections.append("")  # Empty line between files
        
        return '\n'.join(sections)
    
    def _get_severity_icon(self, severity: str) -> str:
        """Get emoji icon for severity."""
        icons = {
            'CRITICAL': '🔴',
            'HIGH': '🟠',
            'MEDIUM': '🟡',
            'LOW': '🟢',
            'INFO': '🔵',
        }
        return icons.get(severity, '⚪')
